### ISSUE TITLE
Possible to build this for the Vita?

### ISSUE THREAD

**Issue by DinisB** [TheKingFireS/Xash3D-COF#13]
Anyways, so i want to play it on the Vita and since there is already Xash3d avaliable for it, is it possible to build it for the vita?

**Comment by TheKingFireS** [comment]
Nope.
1) This is Unkle Mike's Xash3D, that original engine who only supported Windows platform.
2) Cry of Fear is filled with VGUI interface, the problem is there's no source code for VGUI.
3) COF support in Xash3D-FWGS is broken since 2021.
