### ISSUE TITLE
Weird gray line in at the bottom of the screen

### ISSUE THREAD

**Issue by st12q** [TheKingFireS/Xash3D-COF#3]
Windows 11
Happens on 1.0, 1.55 and 1.2
GTX 1070 536.67 Studio
Happens on second PC as well(GTX 660 474.30 Game Ready Windows 10)
Happens on fullscreen and windowed modes (also -fullscreen and -windowed doesn't work for some reason, needed changed window mode manually)
-log -console -game CryOfFear -num_edicts 4096 -gl -launchapp -heapsize 2097152 -32bpp -fullscreen -widescreen -w 1920 -h 1080 -particles 131072 -surfcachesize 6291456 -noforcemparms -noforcemaccel -noforcemspd -fps_max 144
![wronf2](https://github.com/TheKingFireS/Xash3D-COF/assets/87384659/f3659757-0622-4a01-beb8-41ee6c317392)
[engine.log](https://github.com/TheKingFireS/Xash3D-COF/files/12872577/engine.log)

**Comment by TheKingFireS** [comment]
Turn out, COF included config.cfg, it had ``viewsize`` which caused this. I'll replaced it with Xash3D converted and generated config.cfg with proper ``viewsize``
