### ISSUE TITLE
OpenGL Error GL_INVALID_VALUE spam in console

### ISSUE THREAD

**Issue by st12q** [TheKingFireS/Xash3D-COF#5]
OpenGL Error: GL_INVALID_VALUE (called at C:\Xash3D\engine\client\gl_rmain.c:832) looping spam error
Windows 11
1.55, 1.0, 1.2
GTX 1070 536.67 Studio
Also happens on second pc with GTX 660 474.30 Game Ready on Windows 10
-log -console -game CryOfFear -num_edicts 4096 -gl -launchapp -heapsize 2097152 -32bpp -fullscreen -widescreen -w 1920 -h 1080 -particles 131072 -surfcachesize 6291456 -noforcemparms -noforcemaccel -noforcemspd -fps_max 144
[engine.log](https://github.com/TheKingFireS/Xash3D-COF/files/12872583/engine.log)

**Comment by st12q** [comment]
It's happens in room with first child with knifes(c_apartment2). And spam happens when looking in direction where child is.
![no spam](https://github.com/TheKingFireS/Xash3D-COF/assets/87384659/a8ee2f20-4ec4-42b3-b758-2fc797e3bb8c)
![spam](https://github.com/TheKingFireS/Xash3D-COF/assets/87384659/608360a4-a23c-4824-be31-476f6789b543)

**Comment by TheKingFireS** [comment]
It's still around even in FWGS's Xash3D. However, I found command that stop checking errors, it's ``gl_check_errors``, so I set it to 0 and it stopped.
